<?php 

$catalog = [
    0 => ["name" => "Vallois",
    "firstname" => "Nicolas",
    "age" => "22",
    "zipcode" => "76600",
    "email" => "bg_du_havre@lamanu.fr",
    "preference" => "femme",
    "gender" => "homme",
    "picture" => "nicolas.jpg",
    "description" => "Si tu ressembles à Zero Two, tu m'intéresses aussi."]
,    
    1 => ["name" => "Menvusa",
    "firstname" => "Gérard",
    "age" => "40",
    "zipcode" => "76600",
    "email" => "optic4000@gmail.com",
    "preference" => "femme",
    "gender" => "homme",
    "picture" => "gerard.jpeg",
    "description" => "Je sais déjà que tu vas me taper dans l'oeil 🤓."]
,
    2 => ["name" => "Bayne",
    "firstname" => "Bruce",
    "age" => "35",
    "zipcode" => "76600",
    "email" => "parmabarbe@batman.com",
    "preference" => "femme",
    "gender" => "homme",
    "picture" => "bruce.jpg",
    "description" => "Je ne dis pas que je suis Batman, juste qu'on l'a jamais vu en même temps que moi."]
,
    3 => ["name" => "Traen",
    "firstname" => "Alexandre",
    "age" => "22",
    "zipcode" => "60420",
    "email" => "ouraipmaster@lamanu.fr",
    "preference" => "femme",
    "gender" => "homme",
    "picture" => "alexis.jpg",
    "description" => "A la recherche de ma dulcinée pour partager des Mc Wraps en tête à tête. Fan de js, s'abstenir."]
,
    4 => ["name" => "Jobs",
    "firstname" => "Jean-Michel",
    "age" => "33",
    "zipcode" => "75002",
    "email" => "apple4ever@lamanu.fr",
    "preference" => "homme",
    "gender" => "homme",
    "picture" => "jobs.jpg",
    "description" => "Votre temps est limité, ne le gâchez pas en menant une existence qui n'est pas la vôtre."]
,
    5 => ["name" => "Binks",
    "firstname" => "Ken",
    "age" => "45",
    "zipcode" => "31000",
    "email" => "missamissa@lamanu.fr",
    "preference" => "homme",
    "gender" => "homme",
    "picture" => "ken.jpg",
    "description" => "Missa déteste war press, jamais cherché bisbille! La clé Ousséké la clé de mon keur? La!"]
,
    6 => ["name" => "Triangle",
    "firstname" => "Mariah",
    "age" => "50",
    "zipcode" => "76600",
    "email" => "jaimechanter@hotmail.fr",
    "preference" => "homme",
    "gender" => "femme",
    "picture" => "mariah.jpg",
    "description" => "J'ai une grande passion pour Noël. Toute l'année. Tout le temps."]
,
    7 => ["name" => "Ozaur",
    "firstname" => "Amandine",
    "age" => "87",
    "zipcode" => "76600",
    "email" => "minitel@wanadoo.fr",
    "preference" => "homme",
    "gender" => "femme",
    "picture" => "amandine.jpg",
    "description" => "J'ai connu une époque sans internet."]
,
    8 => ["name" => "Bellossi",
    "firstname" => "Monica",
    "age" => "56",
    "zipcode" => "76600",
    "email" => "monicaB@gmail.com",
    "preference" => "homme",
    "gender" => "femme",
    "picture" => "monica.jpg",
    "description" => "Recherche homme sérieux. Les fans de Seigneur des anneaux, s'abstenir."]
,
    9 => ["name" => "Poirson",
    "firstname" => "Ivy",
    "age" => "25",
    "zipcode" => "40404",
    "email" => "loveisp0ison@lamanu.fr",
    "preference" => "homme",
    "gender" => "femme",
    "picture" => "ivy.jpg",
    "description" => "La dernière fleur que tu croisera sur ton chemin 🥀."]
,
    10 => ["name" => "Cartapus",
    "firstname" => "Chantal",
    "age" => "40",
    "zipcode" => "61302",
    "email" => "camouflage@lamanu.fr",
    "preference" => "femme",
    "gender" => "femme",
    "picture" => "chantal.jpg",
    "description" => "Là on me voit, là on me voit plus, on me voit un peu, on me voit plus."]
,
    11 => ["name" => "Grande",
    "firstname" => "Ariana",
    "age" => "25",
    "zipcode" => "60420",
    "email" => "lovefarmers@lamanu.fr",
    "preference" => "homme",
    "gender" => "femme",
    "picture" => "ariana.jpg",
    "description" => "Hey guys, this is Ariana and I love french devs! Especially Alexandre!"]

];
